### ISSUE TITLE
bug poormaps>OSMS-server 

### ISSUE THREAD

**Issue by Caballlero** [rinigus/geocoder-nlp#21]
HELLO RINIGUS 
- thank you for your immense work on OSMSserver
- I just want to notify you of the words TARGET-START Continue showing in poormaps navigation.

**Comment by rinigus** [comment]
Hi and you are welcome!

@Caballlero, yes, its still there. I have opened a bug at https://github.com/rinigus/osmscout-server/issues/51 . It should be translatable, as far as I understand, but I would like to replace it with the address, as stated in that issue. 

Would you mind if we move our conversation regarding that over to the server repo? 

cheers,

rinigus

**Comment by Caballlero** [comment]
yes ,sorry i forgot it  ;  \

**Comment by rinigus** [comment]
No problem - its always better to report than keep quiet :) . I'll close it here, but would work it over in osm scout server issue.
