### ISSUE TITLE
add support for postal codes

### ISSUE THREAD

**Issue by rinigus** [rinigus/geocoder-nlp#38]

**Comment by rinigus** [comment]
for UK: https://www.freemaptools.com/download-uk-postcode-lat-lng.htm

**Comment by otsaloma** [comment]
For what it's worth, OpenCage [seems](https://geocoder.opencagedata.com/credits) to use [postcodes.io](http://postcodes.io/). They have the data on [GitHub](https://github.com/ideal-postcodes/postcodes.io/tree/master/data).

**Comment by rinigus** [comment]
https://postcodeaddressfile.co.uk/ for UK data

**Comment by rinigus** [comment]
Support for postal codes added through the latest commits, closing
