### ISSUE TITLE
Impossible to find exact address matches in Italy

### ISSUE THREAD

**Issue by Orologiaio** [rinigus/geocoder-nlp#39]
Searching for addresses with OSM Scout + WhoGo maps never returns an exact match. I've tried this with few addresses I use often. With a bit of luck I am able to get results near the desired address, but the are all POIs (mainly bus stops that have the name of the street I'm searching, or in other cases small business activities that also, for same reason, have the name of the street in their name.

I sent a private mail to rinigus with a log and some examples including sensible data I don't want to publicly share here.

**Comment by rinigus** [comment]
Turned out to be due to OSM lacking these particular house numbers. Has to be fixed by adding house numbers to OSM. Closing here
