### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by missinglink** [rinigus/geocoder-nlp#49]
Hi @rinigus 

I tried to find contact detail for you online but came up blank :)

I think there might be a possibility for some collaboration as we are working in similar areas.
Please send me an email if you'd like to catch up (either video call or in-person in Berlin).

You can find my contact details on my GitHub profile.

-P

**Comment by rinigus** [comment]
Sent direct email, closing as an issue. Please let me know if the email didn't manage to get through.

BW,

Rinigus
