### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by aravindpadu** [rinigus/geocoder-nlp#51]
hey can you please provide step by step procedure for libpostal language specific installation

**Comment by rinigus** [comment]
If you mean generation of the datasets, then see README at https://github.com/rinigus/geocoder-nlp/tree/master/scripts/postal

If you mean how to use them, see source code of  https://github.com/rinigus/geocoder-nlp/blob/master/demo/main.cpp

Prepared datasets are available via OSM Scout Server (https://github.com/rinigus/osmscout-server), as a part of complete package providing map tiles, search, and routing.

So, please let me know if something is missing in instructions.

**Comment by rinigus** [comment]
They are attached to https://github.com/openvenues/libpostal/releases/tag/v1.0.0 in libpostal release. See archives attached to it.

**Comment by aravindpadu** [comment]
so i  need to fetch data from s3 right

**Comment by rinigus** [comment]
Yes. Since its an issue regarding libpostal datasets, I am closing it as an issue of the geocoder. Which doesn't prevent you from asking/discussing it over here after that.

**Comment by aravindpadu** [comment]
hi rinigus,
I have downloaded all the files reuired but unable to fin geonames.tsv and
postal_codes.tsv .
Do i need to download
*openaddresses_formatted_addresses_tagged.random.tsv.gz* ?

**Comment by rinigus** [comment]
Sorry, I pointed you to the wrong datasets. For training, see https://github.com/openvenues/libpostal#parser-training-sets

**Comment by aravindpadu** [comment]
hey i got this error during make -j 16
 "./build_country_db.sh: line 109: build_geodb: command not found"
i  made sure that path to postal src is correct . Can u please check if it
is working for u

**Comment by rinigus** [comment]
Indeed, the latest version of the scripts was not committed. Please check again
