### ISSUE TITLE
Key did not exist error on rebuilding libpostal model

### ISSUE THREAD

**Issue by TurboCar** [rinigus/geocoder-nlp#63]
I found a "Key did not exist" error when trying to leverage the script under postal folder to rebuild new libpostal model that includes multiple countries. Does anyone run into the same problem? thanks!
 
![Screen Shot 2022-03-22 at 13 12 26](https://user-images.githubusercontent.com/30210344/159413169-99c3a7a2-546f-483c-b83e-62dfe399c664.png)

**Comment by rinigus** [comment]
Please specify in details what you did and how to reproduce it

**Comment by TurboCar** [comment]
Thanks for your replying. The goal of retraining is to improve the accuracy of full-size model on UK addresses. Here are my steps:
1. Append two bad UK addresses into uk_openaddresses_formatted_addresses_tagged.random.tsv. for example, 

> en	gb	Santoga/house Auto/house Ellis/road Ashton/road Street/road Huyton/suburb Liverpool/city L55/postcode 6BK/postcode United/country Kingdom/country
> en	gb	1500/house_number Eureka/road Park/road Lower/suburb Pemberton/suburb Ashford/city Kent/state_district TN25/postcode 4BF/postcode United/country Kingdom/country

2. Modified build_country_db.sh to re-train full-size mode based on original datasets. The code changes like:

![Screen Shot 2022-03-23 at 07 53 00](https://user-images.githubusercontent.com/30210344/159596697-e5a8ba8b-067b-42f3-b1d0-8404a935d374.png)

3. Run the bash script on a VM machine with 144GB memory & 700 GB free disk. I just found the 'Key did not exist' error every time there were 5,400,000 added to trie. If run the script with single country, i.e., GB only, there was no any issue found.

**Comment by rinigus** [comment]
But that sounds like libpostal bug, if anything. Assuming that I understood it right

**Comment by rinigus** [comment]
Closing over here, assuming that it is not an issue of the geocoder
